<a href="https://colab.research.google.com/github/para18952/cursoPython2025/blob/dia_2/Modulo1_b/01.numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/para18952/cursoPython2025.git

Cloning into 'cursoPython2025'...
remote: Enumerating objects: 364, done.
remote: Counting objects: 100% (364/364), done.
remote: Compressing objects: 100% (259/259), done.
remote: Total 364 (delta 141), reused 216 (delta 87), pack-reused 0 (from 0)
Receiving objects: 100% (364/364), 24.53 MiB | 7.71 MiB/s, done.
Resolving deltas: 100% (141/141), done.
Updating files: 100% (124/124), done.


In [2]:
import os
file_path=("/content/cursoPython2025/Modulo1_b/")

## NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [3]:
import numpy as np
from PIL import Image

In [4]:
lista = [1, 2, 3]

In [5]:
type(lista)

list

In [6]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

numpy.ndarray

### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [7]:
vector = [-2, 4, 1, 3.5]

vector = np.array(vector)


In [8]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

0
1


In [9]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

[-2.   2.   3.   6.5]
[ -2.  -8.  -8. -28.]


In [10]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(2, 2)

matriz_1

array([[-2. ,  4. ],
       [ 1. ,  3.5]])

In [11]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .T

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[-2.   1. ]
 [ 4.   3.5]]
--------------------
[[-2.   1. ]
 [ 4.   3.5]]


In [13]:
# .tolist() retorna el array en una lista

matriz_1.tolist()

[[-2.0, 4.0], [1.0, 3.5]]

In [ ]:
#vector

In [ ]:
#matriz_1

In [ ]:
# .flatten() retorna un vector plano con los elementos de la matriz

#matriz_1.flatten()

In [ ]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

#print("Antes de .sort()", vector)

#vector.sort()

#print("Después de .sort()", vector)

In [ ]:
#vector

In [ ]:
# .ndim retorna el número de dimensiones

#vector.ndim

In [ ]:
# .size retorna el número de elementos

#vector.size

In [ ]:
# .shape retorna en una tupla las dimesiones de la matriz

#matriz_1.shape

In [ ]:
# .dtype retorna el tipo de dato de los elementos de la matriz

#vector.dtype

### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [ ]:
matriz = np.array([[1, 2, 3, 10],
                   [4, 5, 6, 20],
                   [7, 8, 9, 30]])

matriz

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [ ]:
#print(matriz)

In [ ]:
#matriz.flatten()

In [ ]:
#matriz.reshape(6, 2)

In [ ]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

#empty = np.empty(shape = (5, 5), dtype = "int") #float

#print(empty)

In [ ]:
# Inicializa una matriz de 1's.

#ones = np.ones(shape = (5, 5), dtype = "int8")

#print(ones)

In [ ]:
# Inicializa una matriz de 0's.

#zeros = np.zeros(shape = (5, 5), dtype = "int8")

#print(zeros)

In [ ]:
# Matriz identidad

#np.eye(5)

In [ ]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

#full = np.full((5,), range(5))

#print(full)

In [ ]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

#linspace = np.linspace(1, 12, 16)

#print(linspace)

### Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [ ]:
matriz = np.array([[1, 0, 0, 0, 0],
                   [0, 0, 2, 0, 0],
                   [1, 1, 0, 0, 1],
                   [2, 1, 1, 1, 0],
                   [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [ ]:
# Hacer

#matriz[4][1]

In [ ]:
# Es igual que hacer

#matriz[4, 1]

In [ ]:
# Slicing
matriz[1:4, 1:4]

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [ ]:
# Slicing + Indexing

#matriz[[fila1, fila2], [columna1, columna2]]

matriz[[1, 4], [1, 4]]

array([0, 2])

### Operaciones con Arrays

In [ ]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


In [ ]:
# Suma

A + B

In [ ]:
# Resta
A - B

In [ ]:
# Multiplicación por escalar

A * 5

In [ ]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

In [ ]:
# División por escalar

A / 5

In [ ]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

In [ ]:
print(A)
print("-"*20)
print(B)

#### Concatenar

In [ ]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0);

In [ ]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1);

### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                        

In [ ]:
#np.random.random(5) # un array de 5 elementos
#np.random.random(size = (5, 5)) # una matriz de 5x5


In [ ]:
#print(np.random.random());

#print("-"*30);

#print(np.random.random(5));

In [ ]:
#print(np.random.rand())

#print("-"*30)

#print(np.random.rand(2, 3))

In [ ]:
#print(np.random.randint(0, 10))

#print("-"*30)

#print(np.random.randint(1, 10, size = (5, 5)))

## Nota
numpy también sirve para trabajar con **cadenas de texto**, pero se recomienda hacerlo mejor con pandas

In [ ]:
frutas = np.array(["manzana", "banana", "pera", "manzana", "uva"])

In [ ]:
#Comparar (elementos iguales a algo)
frutas == "manzana"

array([ True, False, False,  True, False])

In [ ]:
# Entonces podremos seleccionar
solo_manzanas = frutas[frutas == "manzana"]
solo_manzanas

array(['manzana', 'manzana'], dtype='<U7')

In [ ]:
# numpy también sirve para trabajar con cadenas de texto, pero se recomienda hacerlo mejor con pandas
print(np.random.choice(a = ["a", "e", "i", "o", "u"],size = 10, p = [0.6, 0.1, 0.1, 0.1, 0.1]))

['a' 'a' 'e' 'a' 'a' 'a' 'o' 'a' 'o' 'a']


In [ ]:
np.random.seed(0)# Para generar una semilla y tener siempre el mismo valor "aleatorio"

In [ ]:
# Para generar una semilla y tener siempre el mismo valor "aleatorio"
np.random.seed(0)


In [ ]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

#np.set_printoptions(formatter = {"float" : lambda x: "{0:0.2f}".format(x)})

#np.random.randn(6, 6)

In [ ]:
#np.random.randn(6, 6)

In [ ]:
#np.empty((5, 5), dtype = "float64")

In [ ]:
#################################################################################################################################################################################################

In [ ]:
# Cargar imagen en blanco y negro
imagen = Image.open(file_path+"letra_A.jpg").convert("L")  # Convertir a escala de grises


array([[1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]])