<a href="https://colab.research.google.com/github/para18952/cursoPython2025/blob/dia_2/Modulo1_b/02.numpy_1_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicios NumPy 1

In [1]:
import numpy as np

### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [2]:
# Crea un vector con 10 elementos pares.
vector_pares = np.arange(2, 21, 2)
print(vector_pares)

[ 2  4  6  8 10 12 14 16 18 20]


### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [10]:
tam = vector_pares.shape
print("Tamaño: ", tam[0])

Tamaño:  10


In [6]:
numDim = vector_pares.ndim
print("Numero de dimensiones: ", numDim)

Numero de dimensiones:  1


### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **`list comprehension`** y conviertelos en una matriz de (5, 2) dimensiones.

In [14]:
listaPares = [i for i in range(2, 11, 2)]
listaImpares = [i for i in range(1, 10, 2)]
print(listaPares)
print(listaImpares)
matriz = np.array([listaPares, listaImpares])
print(matriz)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [12]:
listaPares =[2, 4, 6, 8, 10]
listaImpares = [1, 3, 5, 7, 9]
matriz = np.array([listaPares, listaImpares])
print(matriz)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [15]:
tipo = matriz.dtype
print(tipo)

int64


### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [18]:
matrizCeros4Dim = np.zeros((4, 4))
#print(matrizCeros4Dim)

#Poner la diagonal principal con 5
np.fill_diagonal(matrizCeros4Dim, 5)
print(matrizCeros4Dim)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### Ejercicio 6:
- Utiliza la función **`np.linspace()`** para crear un vector con 10 elementos entre los números: -5 y 5.

In [19]:
#función np.linspace() para crear un vector con 10 elementos entre los números: -5 y 5.
vector = np.linspace(-5, 5, 10)
print(vector)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [26]:
# matriz vacía de tamaño (3, 6) con elementos del tipo flotante.
matrizVacia = np.empty((3, 6), dtype=float)
print(matrizVacia)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

In [34]:
# función generarNumerosPrimos
def generarNumerosPrimos(n):
  primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653]
  #print("Número de primos: ", len(primos))
  if n <= 0:
    return []
  elif n <= 119:
    return primos[:n]
  else:
    return []

# Convertir matriz anterior en matriz de una dimension
matrizVacia = generarNumerosPrimos(18)

#Convertir lista en matriz
matrizVacia = np.array(matrizVacia)
matrizVacia = matrizVacia.reshape(3, 6)
print(matrizVacia)


[[ 2  3  5  7 11 13]
 [17 19 23 29 31 37]
 [41 43 47 53 59 61]]


### Ejercicio 9:
- Reemplaza los números que estan dentro de un circulo por un 99 utilizando slicing.
<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_1.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>




### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

### Ejercico 11:
- Obten la tercera columna de la matriz.

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

### Ejercicio 14:
- Aplica la función **`np.flatten()`** a la matriz anterior para obtener un vector.

### Ejercicio 15:
- Aplica el método **`.reshape()`** al vector anterior para obtener una matriz de (1, 4) dimensiones.

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.