<a href="https://colab.research.google.com/github/para18952/cursoPython2025/blob/dia_3/Modulo1_b/04.numpy_2_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicios NumPy 2

In [1]:
import numpy as np
import datetime

### Ejercicio 1:
- Obten un vector con 12 elementos aleatorios, los primeros 6 elementos deben de ser negativos y los siguientes 6 elementos positivos.

In [8]:
vector = ()
vector = np.random.randn(12)
#Verificar si los primeros 6 son negativos
for i in range(6):
    if vector[i] > 0:
        vector[i] *= -1
#Verificar si los siguientes 6 son positivos
for i in range(6, 12):
    if vector[i] < 0:
        vector[i] *= -1

vector

array([-0.37612201, -0.19782539, -1.89309804, -0.61727169, -1.2464973 ,
       -1.30694401,  0.34352971,  0.85497995,  0.64434399,  0.54571014,
        0.40637835,  1.18480216])

In [10]:
vector = np.random.randn(12)
#igual que el anterior, pero uniendo los for
for i in range(12):
    if i < 6:
        if vector[i] > 0:
            vector[i] *= -1
    else:
        if vector[i] < 0:
            vector[i] *= -1
vector



array([-0.54476056, -0.92780437, -0.28933868, -0.82193812, -0.29926863,
       -0.73990614,  0.72629705,  1.25180084,  2.24820322,  0.52582269,
        0.89726438,  0.46730752])

In [13]:
vector = np.random.randn(12)
# se puede comprimir en una línea el for (para los 12 elementos)
vector1 = np.where(vector[:6] > 0, vector[:6] * -1, vector[:6])
vector2 = np.where(vector[6:] < 0, vector[6:] * -1, vector[6:])
vector = np.concatenate((vector1, vector2))
vector

array([-0.41439646, -0.10760867, -0.22528117, -0.7489352 , -0.30591208,
       -0.68893713,  0.4043139 ,  1.61220308,  1.01814502,  0.9902932 ,
        0.45106055,  1.46760181])

In [24]:
#vector = np.random.randn(12)
vector = np.random.randint(-1000, 1000, 12)
print ("Vector antes: ", vector,"\n")
vector = np.concatenate((np.where(vector[:6] > 0, vector[:6] * -1, vector[:6]), np.where(vector[6:] < 0, vector[6:] * -1, vector[6:])))
print ("Vector después: ", vector)

Vector antes:  [ 836  243  195 -623 -570  251 -235 -849 -119 -202 -517  -98] 

Vector después:  [-836 -243 -195 -623 -570 -251  235  849  119  202  517   98]


In [22]:
#vector de 12 enteros aleatorios entre -1000 y 1000
vector = np.random.randint(-1000, 1000, 12)
print ("Vector antes: ", vector,"\n")

Vector antes:  [-799  951 -897  554 -929  424  -18  361  581 -538 -555 -139] 



### Ejercicio 2:
- Obten una matriz con dimensiones igual a (3, 5) con valores flotantes entre 0 y 1 para cada elemento.

### Ejercicio 3:
- Obten una matriz con dimensiones igual a (4, 4), cada elemento de la matriz debe de ser un número aleatorio entre 1 y 5.

### Ejercicio 4:
- Obten una matriz de dimensiones (7, 7) de ceros y si la suma de sus indices es par convierte el valor en 1.

In [ ]:
import numpy as np

np.zeros((7, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Después de crear la matriz anterior (matriz) ejecuta esta celda para observar a través de una imagen el resultado.

import matplotlib.pyplot as plt

plt.figure(figsize = (5, 5))
plt.imshow(matriz, cmap = "gray")
plt.show()

### Ejercicio 5:
- Obten la siguiente matriz:

<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_2.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>



### Ejercicio 6:
- Obten la siguiente matriz:

<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_3.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>



### Ejercicio 7:
- Obten una matriz con dimensiones igual a (4, 7), el primer elemento de la matriz debe de ser el día de hoy y para los siguientes elementos los próximos días.

### Ejercicio 8:
- Repite el ejercicio anterior pero el día de hoy debe de iniciar en la celda [0][4] y para los siguientes elementos los próximos días. Respecto a los elementos [0][0:4], agrega los días anteriores al día de hoy.

### Ejercicio 9:
- Obten el calendario de julio como se muestra en la imagen:

<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_4.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>




### Ejercicio 10:
- Obten una matriz con el calendario de junio, julio y agosto, como se muestra en la imagen:

<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_5.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>



### Ejercicio 11:
- A partir de la matriz anterior obten la matriz de junio, julio y agosto haciendo slicing. Guarda cada mes en una variable.

### Ejercicio 12:
- Suma las matrices de junio y julio, aplica la transpuesta, convierte la matriz en un vector, obten la suma acumulada del vector y divide todos los elementos entre el valor máximo del vector.

### Ejercicio 13:
- Escribe un código que se pueda utilizar para generar este tipo de matrices automaticamente y aumenta la dimension de la matriz para observar los resultados como en la figura.

<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_6.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>



<center>
 <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_7.png?raw=true" alt="descriptiva" width="50%" height="50%">  
</center>

